const styles = (theme) => ({
  root: {
    flexGrow: 1,
  },

  background: {
    // flexGrow: 1,
    backgroundColor: '#010102',
    width: '101%',
    height: '106vh',
  },
  movieHero: {
    position: 'relative',

    // height: (props) => (props.height ? props.height : '100%'),
    height: '60vh',
    marginBottom: '1.5%',
    marginTop: '-1.5%',
    // marginTop: '1%',
    width: '100%',
    color: theme.palette.common.white,
    backgroundColor: theme.palette.background.dark,
    // borderBottom: '4px solid white',
  },
  blurBackground: {
    position: 'absolute',
    top: 0,
    height: '56vh',
    right: 0,
    backgroundSize: 'cover',
    backgroundRepeat: 'no-repeat',
    marginTop: '2%',
    width: '65%',
  },
  infoSection: {
    marginTop: '1%',
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: '60vh',
    backgroundBlendMode: 'multiply',
    background:
      'linear-gradient(to right, rgba(0,0,0,2) 34%, transparent 100%)',
    zIndex: 2,
    marginTop: '-4%',
  },
  coverContentHolder: {
    position: 'relative',
    maxWidth: '60%',
    'text-align': 'left',
    marginBottom: '-5%',
  },
  miviLogo: {
    marginTop: '0%',
    marginLeft: '-.5%',
    'margin-bottom': '-2.5%',
    font: '300 220% Roboto, sans-serif',
    color: '#e50a15',
    // color: '#ffcb01',
    // color: '#b11f25',
    'letter-spacing': '-1.5px',
  },
  movieTitle: {
    //  '&:hover': {
    //   transition: '.2s',
    //   'box-shadow': ' -1px 1px 35px -17px rgba(255,255,255,1)',
    //   border: '2px solid white',
    //   transform: 'scale(1.07)',
    // },
    transition: '.5s',
    maxWidth: '70%',
    textTransform: 'uppercase',
    // textTransform: 'capitalize',
    marginLeft: '3.0%',
    marginTop: '1%',
    font: '400 170% Roboto, sans-serif',
    'letter-spacing': '-.5px',
  },

  description: {
    marginTop: '0%',
    // marginBottom: '-7%',
    color: '#fff',
    lineHeight: 1.4,
    minHeight: '25vh',
    // 'word-spacing': '1px',
    'letter-spacing': '.5px',
    maxWidth: '70%',
    font: '300 90% Roboto, sans-serif',
  },
  directedTimeGenres: {
    marginTop: '-6%',
    marginBottom: '8%',
    width: '110%',
  },
  director: {
    color: 'white',
    font: '300 100% Roboto, sans-serif',
    marginTop: '-3%',
    display: 'inline-block',
  },
  timeIcon: {
    marginBottom: '-6%',
    // marginRight: '1%',
    'font-size': '20px',
    paddingRight: '3%',
    marginLeft: '-50%',
    color: '#fff',
  },
  duration: {
    display: 'inline-block',
    padding: '3%',
    marginLeft: '3%',
    marginRight: '-2%',
    marginTop: '3%',
    font: '300 90% Roboto, sans-serif',
    color: '#fff',
  },
  genre: {
    display: 'inline-block',
    // color: '#cee4fd',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.13)',
    padding: '1%',
    font: '300 90% Roboto, sans-serif',
    marginRight: '2%',
  },

  movieActions: {
    position: 'absolute',
    bottom: 0,
    right: 20,
    // width: '20%',
    display: 'flex',
    zIndex: 100,
  },
  // genreSelector: {
  //   // marginTop: '-30%',
  //   display: 'inline-block',
  //   flex: 1,
  // },

  rating: {
    color: '#fff',
    font: '500 120% Roboto, sans-serif',
    'letter-spacing': '1px',
    // display: 'inline-block',
    flex: 1,
    zIndex: 100,
  },
  button: {
    width: 200,
    height: 70,
    borderRadius: 0,
    zIndex: 2,
  },
  grid: { height: '25%' },
  gridList: {
    transform: 'translateZ(0)',
    flexWrap: 'nowrap',
    // 'overflow-y': 'scroll !important',
    transition: '.5s',
  },
  sectionVideoContainer: {
    display: 'inline-block',
    // position: 'relative',
    // padding: ' 30px 0 56.25% 0',
    marginTop: '-35%',
    marginLeft: '5%',
    // marginBottom: '21%',
  },
  iconLight: {
    'font-size': '50px',
    color: 'white',
    // color: '#e50a15',
    // backgroundColor: 'white',
  },
  sectionVideo: {
    // 'text-align': 'center',
    // margin: 'auto',
    width: '100%',
    // height: '40vh',
    // 'border-radius': '5px',
    // top: 0,
    // left: 0,
    // right: 0,
    // position: 'absolute',
  },
  movieThumbnail: {
    width: '100%',
    height: '37vh',
    paddingTop: '0',
    marginBottom: '1%',
    border: '2px solid #040303',
    transition: '.5s',
    '&:hover': {
      transition: '.3s',
      'box-shadow': ' -1px 1px 35px -17px rgba(255,255,255,1)',
      border: '2px solid white',
      transform: 'scale(1.07)',
    },
  },
});
export default styles;
