const styles = (theme) => ({
  screenBackground: {
    backgroundColor: '#010102',
    width: '101%',
    height: '106vh',
  },
  hero: {
    position: 'relative',
    height: '60vh',
    margin: '-1.5% 0% 1.5% 0%',
    width: '100%',
  },
  blurredCover: {
    position: 'absolute',
    top: 0,
    height: '56vh',
    right: 0,
    backgroundSize: 'cover',
    // backgroundRepeat: 'no-repeat',
    marginTop: '2%',
    width: '65%',
  },
  infoSection: {
    position: 'relative',
    display: 'flex',
    alignItems: 'center',
    width: '100%',
    height: '60vh',
    background:
      'linear-gradient(to right, rgba(0,0,0,2) 34%, transparent 100%)',
    zIndex: 2,
    marginTop: '-4%',
  },
  leftMovieInfoContainer: {
    position: 'relative',
    maxWidth: '60%',
    'text-align': 'left',
    marginBottom: '-5%',
  },
  miviLogo: {
    transition: '.5s',
    margin: '2% 0% -7% -.5%',
    font: '300 220% Roboto, sans-serif',
    color: '#e50a15',
    'letter-spacing': '-1.5px',
  },
  title: {
    transition: '.5s',
    maxWidth: '80%',
    textTransform: 'uppercase',
    margin: '3% 0% -6% 0%',
    font: '400 170% Roboto, sans-serif',
    'letter-spacing': '-.5px',
    color: '#fff',
  },
  iconButton: {
    'font-size': '40px',
    marginBottom: '10%',
    color: '#fff',
    '&:hover': {
      transition: '.5s',
      color: '#e50a15',
    },
  },
  description: {
    marginTop: '0%',
    marginBottom: '-10%',
    color: '#fff',
    lineHeight: 1.4,
    minHeight: '25vh',
    // 'word-spacing': '1px',
    'letter-spacing': '.5px',
    maxWidth: '70%',
    font: '300 90% Roboto, sans-serif',
  },
  directedTimeGenres: {
    margin: '-8% 0% 8% 0%',
    width: '110%',
  },
  directedTimeGenresClose: {
    margin: '-8% 0% 8% 0%',
    width: '110%',
  },
  director: {
    color: 'white',
    font: '300 100% Roboto, sans-serif',
    marginTop: '-3%',
    display: 'inline-block',
  },
  durationIcon: {
    'font-size': '20px',
    paddingRight: '3%',
    margin: '0% 5% -6% -50%',
    color: '#fff',
  },
  duration: {
    display: 'inline-block',
    padding: '3%',
    margin: '3% -2% 0% 3%',
    font: '300 90% Roboto, sans-serif',
    color: '#fff',
  },
  genre: {
    display: 'inline-block',
    color: '#fff',
    border: '1px solid rgba(255,255,255,0.13)',
    padding: '1%',
    font: '300 90% Roboto, sans-serif',
    marginRight: '2%',
  },

  rightMovieInfoContainer: {
    position: 'absolute',
    bottom: 0,
    right: 20,
    display: 'flex',
    zIndex: 100,
  },
  // genreSelector: {
  //   // marginTop: '-30%',
  //   display: 'inline-block',
  //   flex: 1,
  // },
  rating: {
    color: '#fff',
    font: '500 120% Roboto, sans-serif',
    'letter-spacing': '1px',
    flex: 1,
    zIndex: 0,
  },
  // grid: { height: '25%' },
  gridList: {
    transform: 'translateZ(0)',
    flexWrap: 'nowrap',
  },
  trailerContainer: {
    position: 'relative',
    marginTop: '-41.5%',
    marginLeft: '76%',
    zIndex: 300,
  },
  trailer: {
    width: '90vh',
    height: '50vh',
  },
  moviePoster: {
    width: '100%',
    height: '37vh',
    paddingTop: '0',
    marginBottom: '1%',
    border: '2px solid #040303',
    transition: '.5s',
    '&:hover': {
      transition: '.3s',
      'box-shadow': ' -1px 1px 35px -17px rgba(255,255,255,1)',
      border: '2px solid white',
      transform: 'scale(1.07)',
    },
  },
});
export default styles;
